name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.AZURE_ACR_NAME }} --u ${{ secrets.username }} --p ${{ secrets.password }}

    - name: Build and Push Docker Image
      env:
        IMAGE_NAME: my-spring-boot-app 
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME ${{ secrets.AZURE_ACR_NAME }}/my-spring-boot-app:${{ github.sha }}
        docker push ${{ secrets.AZURE_ACR_NAME }}/my-spring-boot-app:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

    - name: Replace tokens for appsettings.json
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: '["**/deployment.yaml"]'
      env: 
        BuildNumber: ${{ github.sha }} 

    - name: update tokens 
      run: |
        bash -c "sed -i 's/BuildNumber/${{ github.sha }}/g'  deployment.yaml"

    - name: Deploy to AKS
      # env:
      #   IMAGE_NAME: ${{ secrets.AZURE_ACR_NAME }}/my-spring-boot-app:${{ github.sha }}
      run: |
        kubectl apply -f deployment.yaml --namespace ingress-nginx